<?php
return [
    'payment_types' => ['cash', 'check', 'e-wallet', 'asset'],
    'case_types' => ['litigation', 'non_litigation'],
    'party_roles' => ['petitioner', 'respondent'],
    'billing_status' => ['paid', 'partially_paid', 'unpaid'],
    'case_status' => ['open', 'in_progress', 'settled', 'won', 'lost', 'archived', 'appeal', 'closed',],
    'contact_types' => ['phone', 'email'],
    'hearing_status' => ['upcoming',  'completed', 'canceled'],
    'notableTypes' => [
        'client' => \App\Models\Client::class,
        'case' => \App\Models\LawCase::class,
        'deposit' => \App\Models\AdminDeposit::class,
        'admin-fee' => \App\Models\AdministrativeFee::class,
        'hearing' => \App\Models\Hearing::class,
        'billing' => \App\Models\Billing::class,
        'billingDeposit' => \App\Models\Deposit::class,
        'associate' => \App\Models\Associate::class,
        'courtBranch' => \App\Models\CourtBranch::class,
        'officeExpense' => \App\Models\OfficeExpense::class,
        'customEvent' => \App\Models\CustomEvent::class,
        'user' => \App\Models\User::class,
    ],
    'contactableTypes' => [
        'client' => \App\Models\Client::class,
        'associate' => \App\Models\Associate::class,
        'case' => \App\Models\LawCase::class,
        'courtBranch' => \App\Models\CourtBranch::class,
        'user' => \App\Models\User::class,
    ],
    'permissionModels' => [
        'Cases' => ['class' => \App\Models\LawCase::class, 'permissions' => ['view', 'create', 'update', 'delete']],
        'Case Deposits' => ['class' => \App\Models\AdminDeposit::class, 'permissions' => ['view', 'create', 'update', 'delete']],
        'Case Expenses' => ['class' => \App\Models\AdministrativeFee::class, 'permissions' => ['view', 'create', 'update', 'delete']],
        'Case Hearings' => ['class' => \App\Models\Hearing::class, 'permissions' => ['view', 'create', 'update', 'delete']],
        'Case Billings' => ['class' => \App\Models\Billing::class, 'permissions' => ['view', 'create', 'update', 'delete']],
        'Case Billing Deposits' => ['class' => \App\Models\Deposit::class, 'permissions' => ['view', 'create', 'update', 'delete']],
        'Clients' => ['class' => \App\Models\Client::class, 'permissions' => ['view', 'create', 'update', 'delete']],
        'Associates' => ['class' => \App\Models\Associate::class, 'permissions' => ['view', 'create', 'update', 'delete']],
        'Office Expenses' => ['class' => \App\Models\OfficeExpense::class, 'permissions' => ['view', 'create', 'update', 'delete']],
        'Custom Events' => ['class' => \App\Models\CustomEvent::class, 'permissions' => ['view', 'create', 'update', 'delete']],
        'Court Brannches' => ['class' => \App\Models\CourtBranch::class, 'permissions' => ['view', 'create', 'update', 'delete']],
    ],
    'activityModels' => [
        'App\Models\LawCase' => ['name' => 'Case', 'attributes' => [
            'case_number' => ['title' => 'Case Number', 'type' => 'string'],
            'case_title' => ['title' => 'Title', 'type' => 'string'],
            'case_type' => ['title' => 'Case Type', 'type' => 'function', 'function' => 'headline'],
            'client_id' => ['title' => 'Client', 'type' => 'function', 'function' => 'getClientName'],
            'party_role' => ['title' => 'Role', 'type' => 'function', 'function' => 'headline'],
            'opposing_party' => ['title' => 'Opposing Party', 'type' => 'string'],
            'total_deposits' => ['title' => 'Total Deposits', 'type' => 'function', 'function' => 'formattedMoney'],
            'total_fees' => ['title' => 'Total Fees', 'type' => 'function', 'function' => 'formattedMoney'],
            'status' => ['title' => 'Status', 'type' => 'function', 'function' => 'headline'],
        ],],
        'App\Models\AdminDeposit' => [
            'name' => 'Deposit',
            'attributes' => [
                'payment_type' => ['title' => 'Payment Type', 'type' => 'string'],
                'amount' => ['title' => 'Amount', 'type' => 'function', 'function' => 'formattedMoney'],
                'deposit_date' => ['title' => 'Deposit Date', 'type' => 'function', 'function' => 'formattedDate'],
            ],
        ],
        'App\Models\AdministrativeFee' => ['name' => 'Expense', 'attributes' => [
            'type' => ['title' => 'Type', 'type' => 'string'],
            'amount' => ['title' => 'Amount', 'type' => 'function', 'function' => 'formattedMoney'],
            'fee_date' => ['title' => 'Expense Date', 'type' => 'function', 'function' => 'formattedDate'],
        ],],
        'App\Models\Hearing' => ['name' => 'Hearing', 'attributes' => [
            'law_case_id' => ['title' => 'Case Number', 'type' => 'function', 'function' => 'getCaseNumber'],
            'title' => ['title' => 'Title', 'type' => 'string'],
            'hearing_date' => ['title' => 'Hearing Date', 'type' => 'function', 'function' => 'formattedDateTime'],
            'court_branch_id' => ['title' => 'Court Branch', 'type' => 'function', 'function' => 'getCourtBranch'],
            'status' => ['title' => 'Status', 'type' => 'string'],
        ],],
        'App\Models\Billing' => ['name' => 'Bill', 'attributes' => [
            'law_case_id' => ['title' => 'Case Number', 'type' => 'function', 'function' => 'getCaseNumber'],
            'title' => ['title' => 'Title', 'type' => 'string'],
            'amount' => ['title' => 'Amount', 'type' => 'function', 'function' => 'formattedMoney'],
            'billing_date' => ['title' => 'Billing Date', 'type' => 'function', 'function' => 'formattedDate'],
            'due_date' => ['title' => 'Due Date', 'type' => 'function', 'function' => 'formattedDate'],
            'total_paid' => ['title' => 'Total Paid', 'type' => 'function', 'function' => 'formattedMoney'],
            'status' => ['title' => 'Status', 'type' => 'string'],
        ],],
        'App\Models\Deposit' => ['name' => 'Payment', 'attributes' => [

            'law_case_id' => ['title' => 'Case Number', 'type' => 'function', 'function' => 'getCaseNumber'],
            'billing_id' => ['title' => 'Bill', 'type' => 'function', 'function' => 'getBilling'],
            'payment_type' => ['title' => 'Payment Type', 'type' => 'string'],
            'defecit' => ['title' => 'Defecit', 'type' => 'function', 'function' => 'formattedMoney'],
            'title' => ['title' => 'Title', 'type' => 'string'],
            'amount' => ['title' => 'Amount', 'type' => 'function', 'function' => 'formattedMoney'],
            'billing_date' => ['title' => 'Billing Date', 'type' => 'function', 'function' => 'formattedDate'],
            'due_date' => ['title' => 'Due Date', 'type' => 'function', 'function' => 'formattedDate'],
            'total_paid' => ['title' => 'Total Paid', 'type' => 'function', 'function' => 'formattedMoney'],
            'status' => ['title' => 'Status', 'type' => 'string'],
            'received_from' => ['title' => 'Received From', 'type' => 'string'],
            'user_id' => ['title' => 'Received By', 'type' => 'function', 'function' => 'getUserName'],
        ],],
        'App\Models\OfficeExpense' => ['name' => 'Office Expense', 'attributes' => [

            'type' => ['title' => 'Type', 'type' => 'string'],
            'description' => ['title' => 'Description', 'type' => 'string'],
            'amount' => ['title' => 'Amount', 'type' => 'function', 'function' => 'formattedMoney'],
            'expense_date' => ['title' => 'Expense Date', 'type' => 'function', 'function' => 'formattedDate'],

        ],],
        'App\Models\CustomEvent' => ['name' => 'Event', 'attributes' => [

            'title' => ['title' => 'Title', 'type' => 'string'],
            'description' => ['title' => 'Description', 'type' => 'string'],
            'type' => ['title' => 'Type', 'type' => 'string'],
            'start_time' => ['title' => 'Start Time', 'type' => 'function', 'function' => 'formattedDateTime'],
            'end_time' => ['title' => 'End Time', 'type' => 'function', 'function' => 'formattedDateTime'],
            'location' => ['title' => 'Location', 'type' => 'string'],

        ],],
    ],
];
